# Written by https://github.com/DeterminateSystems/nix-installer.
# The contents below are based on options specified at installation time.

trusted-users = root bill
substituters = https://nix-community.cachix.org
trusted-public-keys = cuda-maintainers.cachix.org-1:0dq3bujKpuEPMCX6U4WylrUDZ9JyUG0VpVZa7CNfq5E=
