# Written by https://github.com/DeterminateSystems/nix-installer.
# The contents below are based on options specified at installation time.

trusted-users = root bill
extra-substituters = https://nix-community.cachix.org
extra-trusted-public-keys = nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=
# substituters = https://nix-community.cachix.org
# trusted-public-keys = nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=
